sudo: required

services:
  - docker

before_install:
- docker pull akimasa/devkitpro
script:
- docker run --privileged -v /home/travis/build/akimasa/Nintendont:/root/ akimasa/devkitpro /bin/bash /root/travis.sh
before_deploy:
  - git config --local user.name "Akimasa Tateba"
  - git config --local user.email "akimasa@gmail.com"
  - export TRAVIS_TAG="v0-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file:
    - /home/travis/build/akimasa/Nintendont/loader/loader.dol
  on:
    all_branches: true
    tags: false
  skip_cleanup: true
branches:
    except:
      - /^v0-/
#https://github.com/travis-ci/travis-ci/issues/5358#issuecomment-248915326
before_cache:
  # Save tagged docker images
  - mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}' | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
cache:
  bundler: true
  directories:
    - $HOME/docker